view:
  fullscreen: false


cameras:
  max_allowed: 0
  type: picam
  crop_ratio: 0.2
  initial_size: 300
  direction: right
  stretch: false
  list_url: http://192.168.50.139:9001/camlist
  data_url: http://192.168.50.139:9001/cameras/next
  update_interval: 0.1
  list_refresh: 10
  font_ratio: 0.025
  labels: true

  overrides:
    living_room:
      crop_ratio: 0.8
      direction: hcenter
      priority: 1

    garage:
      crop_ratio: 0.8
      direction: hcenter
      priority: 2


  #b'["garage_side","back_bottom","catpod","front_bottom","2049","2048","front_top","back_top"]'