view:
  fullscreen: false
  stretch: false

cameras:
  max_allowed: 0
  type: picam
  crop_ratio: 0.55
  direction: right
  list_url: http://192.168.50.139:9001/camlist
  data_url: http://192.168.50.139:9001/cameras/next
  update_interval: 0.1
  list_refresh: 10

  overrides:

    2048:
      crop_ratio: 1
      direction: center
      priority: 1

    2049:
      crop_ratio: 1
      direction: center