
configuration:
  layout: simple
  generator: default
  view: default

views:
  - id: default
    fullscreen: false
    stretch: false
    font_ratio: 0.025
    labels: true

cameras:
  - id: default
    type: PiCam
    crop_ratio: 0.2
    direction: right

  - id: living_room
    type: PiCam
    name: "Living Room"
    crop_ratio: 0.8
    direction: hcenter

  - id: garage
    type: PiCam
    name: "Garage"
    crop_ratio: 0.8
    direction: hcenter

layouts:
  - id: default
    style_name: fixed
    cols: 3
    rows: 3
    max_allowed: 0
    cameras:
      - id: living_room
        position: (1,3)
      - id: garage
        position: (1,3)

  - id: simple
    style_name: flow
    max_allowed: 0
    cameras:
      - id: living_room
        order: 1
      - id: garage
        order: 2

generators:
  - id: default
    type: PiCamGenerator
    data_url: http://192.168.50.139:9001/cameras/next
    update_interval: 0.1
    list_refresh: 10



  #b'["garage_side","back_bottom","catpod","front_bottom","2049","2048","front_top","back_top"]'