
configuration:
  layout: simple
  generator: default
  view: default

views:
  - id: default
    fullscreen: false
    stretch: false
    fontRatio: 0.025
    labels: true

cameras:
  - id: default
    type: PiCam
    cropRatio: 0.2
    direction: right

  - id: living_room
    type: PiCam
    name: "Living Room"
    cropRatio: 0.8
    direction: hcenter

  - id: garage
    type: PiCam
    name: "Garage"
    cropRatio: 0.8
    direction: hcenter

layouts:
  - id: default
    type: FixedLayout
    cols: 3
    rows: 3
    maxAllowed: 0
    cameras:
      - id: living_room
        position: (1,3)
      - id: garage
        position: (1,3)

  - id: simple
    type: FlowLayout
    maxAllowed: 0
    cameras:
      - id: living_room
        order: 1
      - id: garage
        order: 2

generators:
  - id: default
    type: PiCamGenerator
    dataUrl: http://192.168.50.139:9001/cameras/next
    updateInterval: .1
    listRefresh: 10



  #b'["garage_side","back_bottom","catpod","front_bottom","2049","2048","front_top","back_top"]'