view:
  fullscreen: false

layout:
  max_allowed: 0
  list_refresh: 10
  style: fixed
  cols: 4
  rows: 2
  positions:
    living_room: (1,3)
    deleteme: (1,1)



generators:
  type: picam.PiCamGenerator
  #type: dummy.DummyGenerator
  crop_ratio: 0.2
  initial_size: 300
  direction: right
  stretch: false
  data_url: http://192.168.50.139:9001/cameras/next
  update_interval: 0.1
  list_refresh: 10
  font_ratio: 0.025
  labels: true

  overrides:
    living_room:
      crop_ratio: 0.8
      direction: hcenter
      order: 1
    garage:
      crop_ratio: 0.8
      direction: hcenter
      order: 5
    front_bottom:
      order: 8
    front_top:
      order: 4
#    catpod:
#      order: 7
#    back_top:
#      order: 3
#    garage_side:
#      order:  6
#    back_bottom:
#      order: 2

  #b'["garage_side","back_bottom","catpod","front_bottom","2049","2048","front_top","back_top"]'