
configuration:
  layout: test_fixed
  generator: default
  view: default
  placeholder: offline.gif

views:
  - id: default
    fullscreen: false
    stretch: false
    fontRatio: 0.045
    labels: true
    showCoords: true

cameras:
  - id: default
    type: PiCam
    cropRatio: 0.2
    direction: right

  - id: living_room
    type: PiCam
    name: "Living Room"
    cropRatio: 0.8
    direction: hcenter

  - id: garage
    type: PiCam
    name: "Garage"
    cropRatio: 0.8
    direction: hcenter

layouts:
  - id: default
    type: FlowLayout
    maxAllowed: 0

  - id: fixed
    type: FixedLayout
    cols: 4
    rows: 2
    cameras:
      - id: front_top
        position: (0,0)
      - id: front_bottom
        position: (1,0)
      - id: catpod
        position: (1,1)
      - id: living_room
        position: (0,1)
      - id: back_bottom
        position: (0,2)
      - id: garage_side
        position: (1,2)
      - id: bedroom
        position: (0,3)
      - id: fisheyepi
        position: (0,4)
      - id: garage
        position: (1,4)
      - id: squirrelcam
        position: (1,3)

  - id: test_fixed
    type: FixedLayout
    cols: 2
    rows: 2
    cameras:
      - id: front_top
        position: (0,0)
      - id: front_bottom
        position: (1,0)
      - id: catpod
        position: (1,1)
      - id: living_room
        position: (0,1)

  - id: simple
    type: FlowLayout
    maxAllowed: 0
    cameras:
      - id: living_room
        order: 1
      - id: garage
        order: 2

generators:
  - id: default
    type: PiCamGenerator
    dataUrl: http://192.168.50.139:9001/cameras/next
    updateInterval: .1
    listRefresh: 10